### ISSUE TITLE
Vertical interpolation to pressure levels from CAM hybrid sigma levels

### ISSUE THREAD

**Issue by strandwg** [NCAR/geocat-comp#132]
This functionality would serve the same purpose as the NCL functions "vinth2p*", documented here

https://www.ncl.ucar.edu/Document/Functions/Built-in/vinth2p.shtml

A quirk of those NCL functions is that they can only operate on 2-dimensional lat/lon grids, not the 1-dimensional SE grid that can be used in CAM, so a replacement would need to include that ability.

Thanks!

**Comment by clyne** [comment]
Just a quick note of clarification that the CAM-SE and MPAS dynamical cores both employ unstructured grids that are represented in NetCDF as a 1D NetCDF variable for data with 2 horizontal spatial dimensions, and a 2D NetCDF variable for data with 3 spatial dimensions.

**Comment by dcherian** [comment]
>  as a 1D NetCDF variable for data with 2 horizontal spatial dimensions, and a 2D NetCDF variable for data with 3 spatial dimensions.

Is the vertical dimension a separate "structured" dimension? If so, the existing GeoCAT function should already work as long as the "core dimensions" are specified properly.

**Comment by clyne** [comment]
Correct. The vertical dimension is structured.

**Comment by erogluorhan** [comment]
@strandwg Sorry for the delayed response and thanks for bringing your request!

I would first like to check if you are aware of and had a chance to try GeoCAT's [interp_hybrid_to_pressure](https://geocat-comp.readthedocs.io/en/latest/user_api/generated/geocat.comp.interp_hybrid_to_pressure.html#geocat.comp.interp_hybrid_to_pressure) function, which is Python correspondence for NCL's `vinth2p`. 

As @dcherian and @clyne pointed out, I'd suppose `interp_hybrid_to_pressure` to work for what you asked. Please let me know if you can give it a try or I am happy to run a quick test on any dataset you have.

Orhan - GeoCAT

**Comment by erogluorhan** [comment]
Thanks @andrewgettelman ! It was also mentioned in Issue #207 and we are currently looking into it.
