### ISSUE TITLE
Implementation of ncl sigma2hybrid

### ISSUE THREAD

**Issue by vinodkatmos** [NCAR/geocat-comp#142]
I was wondering if there are plans to translate ncl's sigma2hybrid (https://www.ncl.ucar.edu/Document/Functions/Built-in/sigma2hybrid.shtml) tool by geocat?

**Comment by erogluorhan** [comment]
> Hey, @erogluorhan Thanks a lot. I am looking forward to the new release and using the tool.

Hi @vinodkatmos , thanks a lot! Please have a look at our latest version v2021.10.0, just released on Anaconda and PyPI, and let us know if the function 'interp_sigma_to_hybrid' (for NCL's sigma2hybrid) works fine.

**Comment by vinodkatmos** [comment]
Hi @erogluorhan , 
Thanks a lot.
Probably I am doing something completely wrong. I am not even able to import geocart.comp
Trying to import geocart-comp throws the following error

`ImportError: /u/vinodkum/conda-envs/spyder_env/lib/python3.7/site-packages/geocat/comp/_ncomp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: rgrid2rcm`

I have already tried uninstalling and installing geocart-comp several times.
Are you already aware of this issue?

**Comment by vinodkatmos** [comment]
Hi @erogluorhan , sorry for the late response. It took me some time before I could test interp_sigma_to_hybrid. However, I am facing two difficulties in using this file for WRF_Chem output
1. With the current implementation, it seems not possible to interpolate concentration fields directly. By default, the concentration fields have units of ppm which are not recognised by metpy. We need to convert the units into something that metpy recognizes (e.g. molecules cm-3). See the discussion [here](https://github.com/hgrecco/pint/issues/1277).
2. The current implementation is very slow as compared to ncl. For example, I am interpolating my WRF-Chem absolute humidity fields on TM5 grid. While with ncl, on my machine it took me less than 1 second, with interp_sigma_to_hybrid it took me more than 200s. For your reference, I have attached my ncl script, python scripts and a sample data file [here](https://owncloud.gwdg.de/index.php/s/GXVPAaXeRvpDxrG).

Best regards and thanks a lot,
Vinod

**Comment by erogluorhan** [comment]
Hi @vinodkatmos , thanks a lot for the detailed feedback! We will soon start analyzing these, and your feedback will be much helpful. I will keep you updated!

**Comment by anissa111** [comment]
Hi @vinodkatmos, sorry this looks to have fallen between the cracks. I am going to open a separate issue for issues with `interp_sigma_to_hybrid` and close this issue.
