### ISSUE TITLE
Spherical harmonic routines

### ISSUE THREAD

**Issue by katiedagon** [NCAR/geocat-comp#147]
Are there any GeoCAT versions of the [NCL spherical harmonic routines](https://www.ncl.ucar.edu/Document/Functions/spherical.shtml)? In particular, I'm looking for a python-based solution to the NCL function [gradsf](https://www.ncl.ucar.edu/Document/Functions/Built-in/gradsf.shtml) to compute latitude and longitude gradients on a fixed grid. Thanks!

**Comment by erogluorhan** [comment]
Hi @katiedagon , thanks for reaching out to us! 

Currently there is not any spherical harmonical routine implemented in GeoCAT-comp, but investigating and hopefully implementing `gradsf` would give us an opportunity to dig into the other routines of this family. 

The @NCAR/geocat team is currently investigating it, and we will let you know about our findings.

**Comment by katiedagon** [comment]
Thanks for following up on this @erogluorhan! I will be excited to try out this new GeoCAT functionality.

**Comment by pilotchute** [comment]
@katiedagon 
I've got a jupyter notebook using the upcoming spherical.py functions which (I think) produces the same outputs at gradsf. 

![image](https://user-images.githubusercontent.com/20648306/157614470-cdab4aa2-87d7-4880-b621-777e0d53b5c1.png)

**Comment by katiedagon** [comment]
@pilotchute very cool to see this. Let me know if it would be helpful for me to test anything out in your notebook. Thanks so much for your work on this!

**Comment by pilotchute** [comment]
@katiedagon Sure, how would you like me to send you the notebook?

**Comment by katiedagon** [comment]
If you have the notebook in a github repo you could point me that (or a location on glade)? Or I could wait for the pull request to go through, since I think I'll also need the new geocat-comp code to test the functionality.

**Comment by pilotchute** [comment]
I'll just copy the functions into a notebook, and email it to you.

**Comment by pilotchute** [comment]
Spherical harmonics released.
Issue for spherical gradient feature request in #215

**Comment by pilotchute** [comment]
closing.
