### ISSUE TITLE
calcDayAnomTLL

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#15]
Port the **calcDayAnomTLL** family of functions, including: calcDayAnomTLL. The **calcDayAnomTLL** functions calculates monthly anomalies by subtracting the long term mean from each point (time,lat,lon version)

**Comment by andersy005** [comment]
This was also implemented in #100. `geocat.comp.anomaly()` supports these frequencies:

- `'day'`: for daily anomalies
- `'month'`: for monthly anomalies
- `'year'`: for annual anomalies
- `'season'`: for seasonal anomalies
