### ISSUE TITLE
Unstructured Grid Plotting with CellFill method? 

### ISSUE THREAD

**Issue by whannah1** [NCAR/geocat-comp#165]
I'm a long time NCL/PyNGL user and I'm a huge fan of plotting unstructured grid data on the native grid. In fact, for E3SM development, using the native grid to plot has helped identify problems that are normally washed out when using regridded data. Specifically, I think it is especially valuable to have the "CellFill" mode available in NCL and PyNGL using user provided mesh information, usually from a SCRIP file that can be generated with NCO. This type of plot is NOT currently possible with matplotlib/cartopy and I haven't seen anything acknowledging the need for this in the articles/letters about putting NCL/PyNGL into maintenance mode.

With unstructured grids becoming more common, along with the push for using finite volume physics grids in tandem with spectral element dynamics grids, I think it is VERY important to support this type of plot. I've heard many people mention Delaunay triangulation as an alternative, but is not nearly as useful and is often more computationally burdensome.

**Comment by clyne** [comment]
I just wanted to add that the GeoCAT team has been awarded a three-year NSF grant to provide better support for unstructured grids. The project, called Raijin, should kick off in early fall. We should be making a formal announcement with additional details later this summer.

**Comment by whannah1** [comment]
Something else that might be worth pointing out is that there are very few options for creating an accurate visual representation of spectral element data. The CellFill method in NCL/PyNGL is great for FV data because each data point represents an area average. However, with spectral element data each point represents a nodal value that does not correspond to an area or volume. For dynamics grid data from E3SM and CAM-SE we often make plots using mesh information that has been manufactured such that the area of each polygonal cell matches the weight of the GLL node, but this doesn't really provide an accurate visual representation. 

A more accurate way to handle this case would be to show the smoothness of the SE fields (compared to the "Chunkiness" of FV fields) by shading a color gradient in between the SE nodal points. I think the only tool that can do this is Panopoly, but I've never actually created this type of plot. A smooth looking field could also be achieved by creating a contour plot, but this side steps the need to "see" how the native grid data is laid out and would mask any sort of grid noise problem that might be of interest.

**Comment by erogluorhan** [comment]
Hi @whannah1 ! I'd like to give you a heads up on this: 

We've started working on our Project Raijin, please see its [homepage](https://raijin.ucar.edu/). We are currently developing the [Uxarray](https://github.com/UXARRAY/uxarray) package (as an extension to xarray) to read in and recognize unstructured grid data. 

Even though you seem to be more interested in the visualization aspects of this subject, please feel free to have a look at our [Uxarray tentative API](https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md) and let us know if you have any feedback. We will be starting to investigate/implement visualization functions soon, once we have some reasonable progress on data read-in and important processing functions, i.e. Uxarray.

**Comment by whannah1** [comment]
@erogluorhan glad to hear the Uxarray is underway! I'm actually very interested in the analysis potential of uxarray. Specifically, I'd love to be able to calculate horizontal gradients on the unstructured data. I'll take a look at the API and let you know if I have any feedback.

Also, I'm happy to be a beta tester if you have specific things that are ready (I'm pretty good at breaking things 😉 ).

**Comment by erogluorhan** [comment]
That sounds great! Yes, please feel free to open an issue/discussion for any feedback, e.g. operator request, concerns, corrections, etc.

We will start our Uxarray tests soon after merging our first significant set of functions (mostly dataset read-ins), and I am happy to invite/include you in the process when the time comes.

**Comment by anissa111** [comment]
I'm going to go ahead and close this issue, @whannah1 definitely go check out uxarray! We're always looking for people to kick the tires over there!

Feel free to reopen if there's anything else!

**Comment by whannah1** [comment]
@anissa111 so is this type of plot not going to be supported by geocat?

**Comment by anissa111** [comment]
@whannah1 Not exactly. I closed this issue mostly in routine issue cleaning, as geocat-comp is not where we'd implement such a feature. The GeoCAT team is involved in the development of [uxarray](https://github.com/UXARRAY/uxarray), which is where this type of feature would be implemented.

In short, it's not that we won't look into supporting this type of plot, but that it would go better with Project Raijin's uxarray, which is specifically addressing methods for unstructured grids.

Hope that clarifies things!
