### ISSUE TITLE
module 'geocat.comp' has no attribute 'rgrid2rcm'; cannot import name 'rgrid2rcm' from 'geocat.comp' 

### ISSUE THREAD

**Issue by jaredalee** [NCAR/geocat-comp#199]
Note that I posted this as Issue # 40 in the GeoCAT github (https://github.com/NCAR/GeoCAT/issues/40), because I didn't initially realize the difference between geocat and geocat-comp repositories. So here's my issue:

I'm wondering if anyone can help me here. This is the first time I've tried to use geocat routines in my Python scripts (I'm a former NCL user, but have fully pivoted to Python). I'm trying to regrid data from a rectilinear grid (CAMS) onto a curvilinear grid (CMAQ), so I'm trying to use the routine rgrid2rcm, following the documentation on the webpage (https://geocat-comp.readthedocs.io/en/latest/user_api/generated/geocat.comp.rgrid2rcm.html). Here's the relevant code/pseudo-code snippet:

```
import geocat
import geocat.comp

[ a bunch of lines where I obtain lat/lon and the variable from the rectilinear CAMS data and the lat/lon from the curvilinear CMAQ grid from my data ]

cams_pm25_regrid = geocat.comp.rgrid2rcm(cams_lat, cams_lon, cams_pm25, cmaq_lat, cmaq_lon)
```

Running that yields this error:

`AttributeError: module 'geocat.comp' has no attribute 'rgrid2rcm'`

Then I also tried to add:

`from geocat.comp import rgrid2rcm`

When I do that, then I get this error:

```
Traceback (most recent call last):
  File "regrid_cams_to_cmaq.py", line 30, in <module>
    from geocat.comp import rgrid2rcm
ImportError: cannot import name 'rgrid2rcm' from 'geocat.comp' (/glade/work/jaredlee/python/my_npl_clone_20200417_casper_3.7.5/lib/python3.7/site-packages/geocat/comp/__init__.py)
```

Am I doing something wrong? Or is there a bug? I currently have geocat-comp (2021.10.0) and geocat-f2py (2021.8.0) modules installed. I'm also running on NCAR's Casper, and I just used `pip install geocat-comp --upgrade` to get to version 2021.10.0 before running this. My base Python version is 3.7.5, and I cloned one of the NCAR Python Library packages awhile back so that I could customize packages and upgrades when needed.

Thanks,
Jared

**Comment by jaredalee** [comment]
I was able to resolve this particular issue by loading the new conda-based NCAR Python environment (https://arc.ucar.edu/knowledge_base/83853599). Apparently my old personal clone of a now-deprecated ncar_pylib environment was somehow causing problems, even though I loaded the geocat-comp 2021.10.0 package into it. I would like to suggest that the geocat-comp installation page could be modified to include that specific note for NCAR HPC users, that geocat-comp is automatically installed and ready to use if you load one of the conda-based NCAR Python environments? If a note like that had been there, that would've saved me several hours of troubleshooting.

I'm still getting some errors with my inputs to rgrid2rcm, but that's a separate issue that I'll try to resolve on my own first (and I'll post a new issue if I get stuck).

**Comment by erogluorhan** [comment]
Hi @jaredalee ! 

Is the issue you are having with inputs to `rgrid2rcm`the one you mentioned in Issue #200 or something else? 

In addition, your suggestion of putting NCAR HPC-related info to GeoCAT-comp docs is important! We haven't put any information specific to our own NCAR HPC clusters because GeoCAT toolkits have a worldwide user base. In addition, conda environments might require the user's own attention and updating from time to time as there might be dependeny issues between packages may occur, etc. Therefore, the way you resolved it sounds right to me, and it does not sound like something we can/should document under GeoCAT. However, we would still like to discuss this with the team to see whether we can still do something and provide NCAR folks with any better information.

**Comment by jaredalee** [comment]
Hi @erogluorhan, this particular issue is separate from Issue #200.

I still think including a simple extra note on the webpage for NCAR HPC users would be quite helpful and more user-friendly, as it lowers the bar for being able to start using geocat-comp by avoiding the hassle to create and maintain a separate conda environment just for use with geocat-comp. Other NCAR-developed tools (like NCL) also have a history of including short notes/shortcuts for users on NCAR HPC, while still including full guidance for users on all other systems. But that decision is obviously left up to you and the GeoCAT team, and this issue is now closed from my perspective.

**Comment by erogluorhan** [comment]
> 

Thanks a lot, Jared! This was quite helpful, and we will certainly take this into consideration.
