### ISSUE TITLE
Spherical Gradient Functions.

### ISSUE THREAD

**Issue by pilotchute** [NCAR/geocat-comp#215]
**Describe the feature you'd like added to this project**
Access to xarray compatible spherical gradient functions that are comparable to gradsf, gradsg, etc. from NCL. 

**Link to original NCL functionality, if applicable**
[gradsf](https://www.ncl.ucar.edu/Document/Functions/Built-in/gradsf.shtml)
[gradsg](https://www.ncl.ucar.edu/Document/Functions/Built-in/gradsg.shtml)

**Links to other examples, if applicable**
@katiedagon requested this in the discussion of https://github.com/NCAR/geocat-comp/issues/147

**Describe the solution you'd like**
An implementation of spherical gradients with similar simplifying assumptions and outputs to NCL's gradient functions that support xarray datasets

**Additional context**
[gradsf_W implementation in NCL's sph2W.c](https://github.com/NCAR/ncl/blob/develop/ni/src/lib/nfp/sph2W.c#L1593)

**Comment by pilotchute** [comment]
@katiedagon
I have a gradient function for the wgs84 model in the [gradient](https://github.com/NCAR/geocat-comp/tree/gradient branch)

**Comment by katiedagon** [comment]
Thanks @pilotchute, I will take a look at this [gradient function](https://github.com/NCAR/geocat-comp/blob/gradient/src/geocat/comp/gradient.py) and the notebook that you sent by email.

**Comment by anissa111** [comment]
Closing as completed with #147
