### ISSUE TITLE
web site documentation improvements

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#23]
Installation instructions:

@khallock The documentation describes two options for installing via conda. However, it is not clear that two optional methods are being described. I.e. It’s not clear that the user should pick one method over the other (installing with or without using conda environments)

We should provide a link for more information on managing conda environments

Since matplotlib and cartopy are very likely to be needed for any of our examples we might want to include the conda incantations for installing these. Maybe have a “recommended additional software” section at the end of the conda installation documentation

The bottom half of the installation page seems incomplete, starting with the heading “Required dependencies for building GeoCAT-comp“. What we probably want is a “Installing geo-cat from source” heading that then goes on to describe the installation process for building from source. Of course we should include the caveat that building from source is difficult and is discouraged

Linint2 example script:

@abb58 Is there a reason why different indexing is used for the LAT and LON arrays?

**Comment by abb58** [comment]
@clyne The different indexing for LAT and LON is for a couple of reasons (a) preserve the indexing style in NCL regrid example, (b) provide an example for different ways to indexing.

**Comment by clyne** [comment]
> @clyne The different indexing for LAT and LON is for a couple of reasons (a) preserve the indexing style from NCL regrid example, (b) provide an example for different ways to indexing.

Hmm. Yes, I agree that it would be nice to be consistent with the NCL examples, but arbitrarily using two different indexing mechanisms might cause confusion (I got confused :-). If it is worthwhile to show two different schemes like that it would be helpful to add a comment indicating that they are equivalent.

**Comment by abb58** [comment]
@khallock Upon testing the webpage and installation instructions: I found this:  

`from Cython.Build import cythonize
ImportError: No module named Cython.Build`

I guess, one might require `cython` as well for the list of recommended python packages on the website.

**Comment by khallock** [comment]
@clyne Thanks for the input, I just updated the installation instructions page on the documentation site.
