### ISSUE TITLE
UMBRELLA ISSUE: Lead the GeoCAT-comp content for GeoCAT tutorial

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#239]
Preliminary GeoCAT-comp plan (~1 hr):
1. Current capabilities through docs overview (e.g. analysis categories, functions under each category, etc.)
2. Demo with notebook(s)
    - Hopefully through a permanent GeoCAT-tutorial repository

**Comment by erogluorhan** [comment]
FYI: @pilotchute @hCraker

**Comment by erogluorhan** [comment]
@marodrig Please checkin with @anissa111 to organize things whenever needed .

**Comment by hCraker** [comment]
Now that the tutorial is over, I believe we can close this issue. Great work everyone!
