### ISSUE TITLE
dpres_plevel

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#24]
Port the NCL **dpres_plevel** family of functions, including: dpres_plevel, dpres_plevel_Wrap, linint1_n_Wrap. **dpres_plevel** Calculates the pressure layer thicknesses of a constant pressure level coordinate system.

**Comment by clyne** [comment]
@khallock please verify that documentation is configured correctly to auto-generate read-the-docs doc on geocat website.

**Comment by clyne** [comment]
@erogluorhan please compare example scripts for this function with NCL version of function. If you think it would be helpful, please augment this function with additional examples.

**Comment by appopson** [comment]
Dear all
I am trying to use dpres_plevel from geocat.comp with data given in NCL example [#1](https://www.ncl.ucar.edu/Document/Functions/Built-in/dpres_plevel.shtml). 
I compared output from NCL and from geocat, results seem differents. 

Which is wondering me !!!

`import numpy as np 
import geocat.comp
yplev = np.array([1000.,950.,900.,850.,800.,750.,700.,650.,600., 
        550.,500.,450.,400.,350.,300.,250.,200., 
        175.,150.,125.,100., 80., 70., 60., 50., 
        40., 30., 25., 20.])
ypsfc       = np.array([100*1018]) 

yptop       = min(yplev) 

ydp = geocat.comp.dpres_plevel(100*yplev, ypsfc,  yptop)`

**output from geocat** 

[4300. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000.
 5000. 5000. 5000. 5000. 3750. 2500. 2500. 2500. 2250. 1500. 1000. 1000.
 1000. 1000.  750.  500. 1250.]
 
**output from NCL**  

dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=3750 
dp=2500 
dp=2500 
dp=2500 
dp=2250 
dp=1500 
dp=1000 
dp=1000 
dp=1000 
dp=1000 
dp=750  
dp=500  
dp=750  
dp=500

**Comment by erogluorhan** [comment]
Hi @appopson thanks for sharing your outputs! Since this issue was for the original feature request and had been closed, I have created Issue #350 for the team to follow your issue. Please feel free to chime in there if there is anything new.
