### ISSUE TITLE
Bug: `interp_sigma_to_hybrid` and WRF_Chem output 

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#241]
Hi @erogluorhan , sorry for the late response. It took me some time before I could test interp_sigma_to_hybrid. However, I am facing two difficulties in using this file for WRF_Chem output
1. With the current implementation, it seems not possible to interpolate concentration fields directly. By default, the concentration fields have units of ppm which are not recognised by metpy. We need to convert the units into something that metpy recognizes (e.g. molecules cm-3). See the discussion [here](https://github.com/hgrecco/pint/issues/1277).
2. The current implementation is very slow as compared to ncl. For example, I am interpolating my WRF-Chem absolute humidity fields on TM5 grid. While with ncl, on my machine it took me less than 1 second, with interp_sigma_to_hybrid it took me more than 200s. For your reference, I have attached my ncl script, python scripts and a sample data file [here](https://owncloud.gwdg.de/index.php/s/GXVPAaXeRvpDxrG).

Best regards and thanks a lot,
Vinod

_Originally posted by @vinodkatmos in https://github.com/NCAR/geocat-comp/issues/142#issuecomment-961164064_

**Comment by anissa111** [comment]
I'm going to close this issue, as the performance issues will be included in a different issue shortly.

**Comment by erogluorhan** [comment]
Hey @anissa111 it was closed on Feb 21 but is now assigned to me. I am happy to look into it but just wanted to understand correctly if the intent is actually to work on this now.

**Comment by anissa111** [comment]
Oh, whoops! I think this was a mis-click while trying to archive it in our PL meeting yesterday my bad!
