### ISSUE TITLE
conda-forge support for osx-arm64 platform (Apple Silicon)

### ISSUE THREAD

**Issue by brianpm** [NCAR/geocat-comp#250]
**Describe the feature you'd like added to this project**
I would like to install geocat with conda on an Apple Silicon Mac (i.e. "M1" or "M2" SOC, aka "osx-arm64" platform). For example:
```
conda install geocat-comp
```

**Additional context**
I have been exploring this a bit. It seems like `geocat-comp` itself should be no problem, since it is all python. There might be a slight problem with `geocat-f2py` since it has compiled code. I was able to compile it from source on my machine once I had an environment where I had:
```
conda install gfortran
conda install cxx-compiler
```
as well as the other packages listed at: https://geocat-f2py.readthedocs.io/en/latest/installation.html

My build is not passing the test suite, however, because it says:
`ERROR test/[*].py - AttributeError: module 'numpy' has no attribute 'complex256'`
It says this for all the files, so I replaced their names with `[*].py`. I believe I saw that this issue was already addressed, but I don't immediate see the issue/commit to fix that. 

I don't know the details of adding this to the conda recipe or whatever, but from here:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
it sounds like it is doable ... maybe?

**Comment by marodrig** [comment]
@brianpm Thank you for taking the time to create an issue for the project. We are currently working on compiling f2py for other platforms, including M1/M2 and Windows.

**Comment by erogluorhan** [comment]
@marodrig Looks like this issue is closed automatically thanks to [NCAR/geocat-f2py/ PR #110](https://github.com/NCAR/geocat-f2py/pull/110), but since that PR is reverted with a later PR, I think this issue needs to be reopened, right?

**Comment by marodrig** [comment]
@erogluorhan Yes, this issue needs to be reopened.

**Comment by brianpm** [comment]
I've been watching the GeoCAT changes over the past three months to see if this issue has been addressed. I'm not sure whether the issue is still with geocat-f2py or not, but I am still unable to install geocat-comp with conda: 

```
conda create -n geocat -c conda-forge geocat-comp                                                                                                                                                                      

Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

**Comment by brianpm** [comment]
Hi all,
We just did a quick comparison on two identical MacBook Pros (16-inch, 2021), but the difference is that one was running an old version of conda (4.10.3) and another running the current version (22.11.1). Running the same install command:
```
conda create -n geocat -c conda-forge geocat-comp
```
The **old** version appears to work, but the **new** version fails as described above. 

Please advise whether you think this is a conda issue or a GeoCAT issue. Or maybe it is something else entirely?

**Comment by anissa111** [comment]
This should be done now in v2023.06.0+, as we removed the geocat-f2py namespace import. Please re-open if any issues are encountered
