### ISSUE TITLE
Add unit handling functionality to all of geocat-comp

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#254]
**Describe the feature you'd like added to this project**
Currently, geocat-comp doesn't handle units to insure that calculations are done correctly. It's the responsibility of the user to ensure that they are inputing data in the correct units. Metpy uses `pint` to handle units and do conversions as needed. It would be helpful to add this functionality to geocat-comp so that users don't have to worry about units as much. Conversions can be done behind the scenes.

**Describe the solution you'd like**
Integrate [`pint`](https://pint.readthedocs.io/en/stable/) into our package to check for correct units and do conversions behind the scenes if needed.

**Additional context**
There are murmurs about xarray adding more `pint` integration. We should keep an eye on that.

**Comment by dcherian** [comment]
> There are murmurs about xarray adding more pint integration. We should keep an eye on that.

This already works through [pint-xarray for useful converters](https://pint-xarray.readthedocs.io/en/latest/) and [cf-xarray for UDUNITS support](https://cf-xarray.readthedocs.io/en/latest/units.html)

**Comment by hCraker** [comment]
Wonderful! Thank you for that info @dcherian

**Comment by cyschneck** [comment]
Closed in favor of #479
