### ISSUE TITLE
Vertically Integrated Moisture Flux Convergence (VIMFC)

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#292]
New functionality request: Vertically Integrated Moisture Flux Convergence (VIMFC)

NCL Links:
- Script: https://www.ncl.ucar.edu/Applications/Scripts/mfc_div_1.ncl
- Applications Page: https://www.ncl.ucar.edu/Applications/wind.shtml

Desired functionality:
- python equivalent of above script, both computational and plotting parts
- use above script with WRF data

![image](https://user-images.githubusercontent.com/38434768/201429486-a13c7a98-845b-4e30-8bd0-0ae25f8f3542.png)

Context: request from ESDS Event Breakout

Related NCL functions:
- [uv2dvF_Wrap](https://www.ncl.ucar.edu/Document/Functions/Contributed/uv2dvF_Wrap.shtml)
- [uv2dvF](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dvF-1.shtml)
- [uv2dvG_Wrap](https://www.ncl.ucar.edu/Document/Functions/Contributed/uv2dvG_Wrap.shtml)
- [uv2dvG](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dvG-1.shtml)
- [uv2dv_cfd](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dv_cfd.shtml)

**Comment by hCraker** [comment]
Potentially related paper where the equation above came from https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016GL071026

**Comment by anissa111** [comment]
Potentially relevant ncl-talk discussion: https://mailman.ucar.edu/pipermail/ncl-talk/2019-August/015459.html
