### ISSUE TITLE
Add a "For Developers" section to the website

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#298]
**Describe the feature you'd like added to this project**
This idea was discussed in a related GitHub issue https://github.com/NCAR/geocat-comp/pull/293#issuecomment-1317186940. It would be nice to have a tab on the navigation panel to a "For Developers" page. This page would have information for building documentation and anything else deemed only really useful for contributors and not the general user base.

Possible contents:
- how to build documentation
- explanation of annual/long-term plans for GeoCAT so external contributors know where we are going and how they can help
- how to run pre-commit checks locally

Please add ideas as you see fit.

**Comment by erogluorhan** [comment]
This is generally handled in contributor's guides. However, I can see the motivation for this to give very details to any levels of developers. I'd recommend to

- Have a look at UXarray' s Contributor's Guide as it was recently put together and covered some information like pre-commit

- Discuss if we revise Contributor's Guide instead to cover such information (to some extent without populating it too much for details) or if move on with the idea here

**Comment by hCraker** [comment]
Addressed in #337
