### ISSUE TITLE
UMBRELLA: Overhaul climatology.py and test_climatology.py

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#313]
Various issues dealing with `climatology.py` and its test file have been opened. This is an umbrella issue to help keep track of the status of these files.

- [x] #311 
- [x] #265
- [x] #308
- [x] #314
- [x] #198
- [ ] add explicit support for `numpy.ndarray` as inputs

**Comment by jukent** [comment]
[Dev notes for adding numpy support](https://docs.google.com/document/d/1491taNZF5nc01gb07mPQbvDqbMPliQcMBfo1gBjWKSk/edit?usp=sharing)
