### ISSUE TITLE
geocat.comp.dpres_plevel issue

### ISSUE THREAD

**Issue by appopson** [NCAR/geocat-comp#326]
Dear all
I am trying to use dpres_plevel from geocat.comp with data given in NCL example [#1](https://www.ncl.ucar.edu/Document/Functions/Built-in/dpres_plevel.shtml). 
I compared output from NCL and from geocat, results seem differents. 
_Different size of the output and different results_
Which is wondering me !!!

`import numpy as np`
`import geocat.comp`
```
yplev = np.array([1000.,950.,900.,850.,800.,750.,700.,650.,600.,
550.,500.,450.,400.,350.,300.,250.,200.,
175.,150.,125.,100., 80., 70., 60., 50.,
40., 30., 25., 20.])
```
`ypsfc = np.array([100*1018])`

`yptop = min(yplev)`

`ydp = geocat.comp.dpres_plevel(100*yplev, ypsfc, yptop)`

**output from geocat** 

[4300. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000. 5000.
 5000. 5000. 5000. 5000. 3750. 2500. 2500. 2500. 2250. 1500. 1000. 1000.
 1000. 1000.  750.  500. 1250.]
 
**output from NCL**  
dp=4300 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=5000 
dp=3750 
dp=2500 
dp=2500 
dp=2500 
dp=2250 
dp=1500 
dp=1000 
dp=1000 
dp=1000 
dp=1000 
dp=750  
dp=500  
dp=750  
dp=500

**Comment by anissa111** [comment]
@appopson Interesting! Thank you for your bug report. I will begin looking in to this.

If you could, can you provide an output of `conda list` in the environment you're using?

**Comment by anissa111** [comment]
@appopson, Sorry for the delay, I'm afraid your reply fell through the cracks during January conference season. 

We are currently experiencing an issue with functions housed in the geocat-f2py package through a gepcat-comp pip installation. I suggest you try installing geocat-f2py separately and import the function through that namespace or use conda for your geocat-comp install. 

Additionally, the `dpres_plev` function is currently going through a python-only reimplementation in geocat-comp directly, which will actually fix your issue when it's released anyway. 

Let us know if you still need assistance!

**Comment by jukent** [comment]
@appopson Closing this as a duplicate resolved in https://github.com/NCAR/geocat-comp/issues/350 

Please reach out to me if you have any more questions?
