### ISSUE TITLE
Release v2023.03.0

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#355]
Note: #354 should be addressed first if possible

**Comment by hCraker** [comment]
FYI I also plan on merging a partial fix for the #345 bug before releasing the new version. If you think it's better to wait for a complete solution, I can do that.

**Comment by anissa111** [comment]
I think the temporary solution can be included in this release if you think you'll have time to get it in

**Comment by hCraker** [comment]
v2023.03.0 has been published. I'm waiting for the conda-forge bot to open a PR to release it on conda
