### ISSUE TITLE
Xarray has dropped 3.8, we should do the same

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#380]
In February of this year, [xarray dropped support for python 3.8](https://docs.xarray.dev/en/stable/whats-new.html#v2023-02-0-feb-7-2023). To maintain compatibility with xarray, we should follow suit.

**Comment by anissa111** [comment]
Should we do this since we don't currently have support for 3.11+? We'd only be supporting 3.9 and 3.10, which seems unnecessarily restrictive.

**Comment by hCraker** [comment]
That's a fair point. We could maintain 3.8 support and mention in our documentation that there maybe be limitations by using an older version, but we won't remove it *yet*

**Comment by anissa111** [comment]
I'd be more comfortable removing 3.8 once we get 3.11 (and/or 3.12 when it's available) up and running

**Comment by hCraker** [comment]
Sounds good to me! I'll mark this as a blocked until this conda issue is resolved. https://github.com/conda/conda//issues/11170

**Comment by kafitzgerald** [comment]
Looks like we're unblocked for 3.11 at least:
* https://github.com/actions/python-versions/releases
* https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html

**Comment by anissa111** [comment]
Done as of v2023.06.0
