### ISSUE TITLE
sphinx-book-theme started to break docs

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#394]
**Describe the bug**
Due to pydata-sphinx-theme v0.13.2, the import of `sphinx_book_theme` has started to break. See related: [pydata Issue #711](https://github.com/executablebooks/sphinx-book-theme/issues/711)

**To Reproduce**
See https://readthedocs.org/projects/geocat-comp/builds/19965963/

**Comment by anissa111** [comment]
Release [v1.01](https://github.com/executablebooks/sphinx-book-theme/releases/tag/v1.0.1) of sphinx-book-theme corrected the issue with no necessary intervention. Docs that had failed have been re-run successfully!
