### ISSUE TITLE
Add contributors guide

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#4]
We need to add a complete contributors guide

**Comment by khallock** [comment]
A first draft version of the contributors guide is included in [pull request #1 - linint2](https://github.com/NCAR/geocat-comp/pull/1) in the file [CONTRIBUTING.md](https://github.com/NCAR/geocat-comp/blob/linint2/CONTRIBUTING.md).

In its current state, the guide only contains sections for "Wrapping NComp functions using Cython" and "Wrapping Cython functions in Python". We still need to add more generic information such as:
- how to submit bug reports (use issue templates? provide sample code that broke?)
- how to contribute a new function
  - unit tests
  - documentation
  - usage examples
  - ?
- style guide
- code of conduct

**Comment by erogluorhan** [comment]
Added, please see: [GeoCAT Webpage Contributing](https://geocat.ucar.edu/pages/contributing.html)
