### ISSUE TITLE
CI failures: April 4 2023 

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#400]
The release of pandas 2.0.0 seems to have broken a few things on our side

- we should consider adding pandas to upstream testing

**Comment by anissa111** [comment]
One of our dependencies seems to have pinned to the previous version of pandas, which is why our CI started passing again, I'm going to keep this issue open, as we should still update our package to work with pandas 2.0

**Comment by pilotchute** [comment]
stack trace can be found  
https://github.com/NCAR/geocat-comp/actions/runs/4613451140

**Comment by cyschneck** [comment]
Currently, pandas is pinned to `1.5.3` as part of xarray
```
xarray 2023.2.0 [required: >=0.18.0]
     ├─ numpy 1.23.5 [required: >=1.21]
     │  └─ dependencies of numpy displayed above
     ├─ packaging 23.1 [required: >=21.3]
     │  └─ dependencies of packaging displayed above
     ├─ pandas 1.5.3 [required: >=1.4,<2a0]
     │  └─ dependencies of pandas displayed above
     └─ python 3.11.5 [required: >=3.9]
```

**Comment by cyschneck** [comment]
xarray unpinned as part of #381 (PR: #492) and Upstream-dev CI running against [381 branch completes without error](https://github.com/cyschneck/geocat-comp/actions/runs/6735831146/job/18309883426)

**Comment by cyschneck** [comment]
Expand Upstream-dev CI as part of #507

**Comment by cyschneck** [comment]
Fixed and closed as part of PR https://github.com/NCAR/geocat-comp/pull/492. Expanded tests will part of https://github.com/NCAR/geocat-comp/issues/507 to catch future issues
