### ISSUE TITLE
Change test import logic to make local testing easier

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#413]
@erogluorhan, tagging you as a follow up from our conversation about this last week

Currently, we do imports in our testing files generally like this:
``` python
# Import from directory structure if coverage test, or from installed
# packages otherwise
if "--cov" in str(sys.argv):
    from src.geocat.comp import (whatever)
else:
    from geocat.comp import (whatever)
```

This looks for some sort of install of `geocat.comp` in the environment to run the tests against instead of importing from the file structure, unless running coverage tests. This is clunky for local testing. 

I propose we do something more like the following:
``` python
# Import from directory structure unless running tests on gh actions
if os.environ.get('GITHUB_ACTIONS') == 'true':
    from geocat.comp import (whatever)
else:
    from src.geocat.comp import (whatever)
```

This will allow for import from the file structure in all cases except for when the github actions tests are being run. This will allow for more intuitive local testing while leaving the behaviour for coverage tests and github action tests unchanged.

**Comment by erogluorhan** [comment]
Thanks, Anissa!

```
if os.environ.get('GITHUB_ACTIONS') == 'true':
    from geocat.comp import (whatever)
```

I'd expect to see codecov not being able to analyze the coverage properly with the block above. That's because codecov command is being executed through GH-actions, and with geocat-comp's current namespace/setup configs, codecov couldn't analyze the code through `from geocat.comp import (whatever)`. 

I'd suggest we investigate how we configured uxarray because despite uxarray executing the codecov command through GH-actions, codecov is able to analyze its coverage through `import uxarray as ux` in the test scripts.

**Comment by anissa111** [comment]
@erogluorhan good point! I think I got distracted with the codecov upload and forgot where the upload was coming from 😆

**Comment by anissa111** [comment]
So, I think uxarray is only importing from directory structure. With `print(ux.__file__)` in both environments with and without a local pip install of the package, the source is going to `/Users/anissaz/Desktop/Raijin/uxarray/uxarray/__init__.py`. I think this is less obvious in uxarray because over there we aren't using a `src

**Comment by erogluorhan** [comment]
> So, I think uxarray is only importing from directory structure. With `print(ux.__file__)` in both environments with and without a local pip install of the package, the source is going to `/Users/anissaz/Desktop/Raijin/uxarray/uxarray/__init__.py`. I think this is less obvious in uxarray because over there we aren't using a `src/uxarray` structure like we are here in geocat-comp.

I have an env with a conda-installed uxarray, and `print(ux.__file__)` gives me uxarray through my installed package, not the code directory:

`/Users/oero/miniconda3/envs/uxarray-conda/lib/python3.10/site-packages/uxarray/__init__.py`

Is it not what you experienced?

**Comment by anissa111** [comment]
> I have an env with a conda-installed uxarray ("without a local pip install of the package" as you referred to I believe) and `print(ux.__file__)` gives me uxarray through my installed package, not the code directory:
> 
> `/Users/oero/miniconda3/envs/uxarray-conda/lib/python3.10/site-packages/uxarray/__init__.py`
> 
> Is it not what you experienced?

No, that is still consistent with my expectations. By "without a local pip install" I meant an environment with *no* installed version of the package I was trying to test.

**Comment by erogluorhan** [comment]
> > I have an env with a conda-installed uxarray ("without a local pip install of the package" as you referred to I believe) and `print(ux.__file__)` gives me uxarray through my installed package, not the code directory:
> > `/Users/oero/miniconda3/envs/uxarray-conda/lib/python3.10/site-packages/uxarray/__init__.py`
> > Is it not what you experienced?
> 
> No, that is still consistent with my expectations. By "without a local pip install" I meant an environment with _no_ installed version of the package I was trying to test.

Oh, I see! 

Actually, how is it able to find the `.. \ uxarray` dir from under `\test`? We should be defining that path somewhere else, so the IDE knows, but I couldn't find it.

**Comment by anissa111** [comment]
> Actually, how is it able to find the `.. \ uxarray` dir from under `\test`? We should be defining that path somewhere else, so the IDE knows, but I couldn't find it.

I'm pretty sure we aren't actually, at least not in the codebase. When I set up testing through vscode, I directed it to the test directory from the top level, not the other way around. I actually think pytest/the IDE use the top level directory to run the tests.

**Comment by anissa111** [comment]
Closing this issue in favor of a namespace reorganization
