### ISSUE TITLE
CI Failures: June 7

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#422]
Build links
-----------

Last fully passing CI: https://github.com/NCAR/geocat-comp/actions/runs/5171878464
First failing CI: https://github.com/NCAR/geocat-comp/actions/runs/5205924511

Description of failures
-----------------------
- python 3.8 failures on ubuntu-latest and macos-latest

**Comment by kafitzgerald** [comment]
Curiosity got the better of me and it looks like a pint related failure.  It doesn't seem to be in an environment or requirements file, but it's here: https://github.com/hgrecco/pint/commit/1208b3d503913eabe8ac96db18ee2ad14af1bdd6

And we are testing in Python 3.8 with a pint version (0.22) that has this commit.

**Comment by anissa111** [comment]
Ah, I see, yeah. It looks like pint removed support for 3.8. I'll take another look into just dropping 3.8 I think.
