### ISSUE TITLE
Upstream-dev CI failing after 3.11 update

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-comp#435]
**Describe the bug**
Upstream-dev CI is now failing (sooner than it used to) after the 3.11 update. 
https://github.com/NCAR/geocat-comp/actions/runs/5481409328/jobs/9985673211 

It looks like the conda installs after the upstream dependency installation mess up the environment.  I think it's because the actions workflow config file has Python set to 3.10 and then conda updates it to 3.11 (specified as Python >=3.9 in the conda env file) which removes the upstream dependencies, but not entirely sure.  

Sounds like @philipc2 is seeing something similar over on UXarray and said he'd let us know if he gets to fixing this before us.  It came up earlier today during team time.

**Comment by philipc2** [comment]
https://github.com/UXARRAY/uxarray/pull/369 

It appears that having Python listed explicitly as a dependency in our upstream overrides the version that is set when configuring the environment (i.e. Environment is initialized as Python 3.10, however installing the upstream dependencies bumps it to 3.11).

After removing it as a dependency from the upstream environment, it executes properly.

**Comment by philipc2** [comment]
Additionally, instead of the above solution, we could set the test to run on Python 3.11 instead of 3.10 while keeping Python as a dependency, but personally I don't see why it's necessary to keep Python as a dependency.

**Comment by erogluorhan** [comment]
@anissa111 @kafitzgerald  Any update on this (i.e. draft PR #436)? Please see the PR from UXArray @philipc2 linked before that fixed the same issue there.

**Comment by anissa111** [comment]
> @anissa111 @kafitzgerald Any update on this (i.e. draft PR #436)? Please see the PR from UXArray @philipc2 linked before that fixed the same issue there.

Yep! I'm currently working on improving a lot of our upstream CI. It's not ready for a pull request yet, but you can see my progress on my [branch comparison](https://github.com/NCAR/geocat-comp/compare/main...anissa111:geocat-comp:issue400).

**Comment by erogluorhan** [comment]
> Yep! I'm currently working on improving a lot of our upstream CI. It's not ready for a pull request yet, but you can see my progress on my [branch comparison](https://github.com/NCAR/geocat-comp/compare/main...anissa111:geocat-comp:issue400).

Great, thank you!

**Comment by erogluorhan** [comment]
@anissa111 BTW, I have some ideas about getting rid of `build_envs/upstream-dev-environment.yml` at all and using only the regular `environment.yml` since the actual upstream installation is being handled by the github workflow. You seem like switching to using `environment.yml` in your new branch, so we might already be on the same page. Once your PR is up, we can discuss that though

**Comment by anissa111** [comment]
I do not think this is causing an issue currently. We are installing unreleased versions of several packages in the upstream testing for the purpose of knowing when an upcoming release may break something in our regular CI.

Also, any new version of numpy I think would support python 3.10 as 3.10 is still well within the generally currently supported range. Their [drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) indicates that they won't drop support for 3.10 until April 2025.

**Comment by kafitzgerald** [comment]
> Upstream-dev CI failing at `install geocat-comp` step
> 
> `ERROR: Package 'geocat-comp' requires a different Python: 3.12.0 not in '<3.12,>=3.9'`
> 
> Currently, python version enforced as `python>=3.9, <3.12` in:
> 
> * [setup.cfg:28](https://github.com/NCAR/geocat-comp/blob/main/setup.cfg)
> * [docs.yml:5](https://github.com/NCAR/geocat-comp/blob/main/build_envs/docs.yml)
> * [environment.yml:5](https://github.com/NCAR/geocat-comp/blob/main/build_envs/environment.yml)

Looks like this is the prior issue now getting worse.  

@philipc2's fix in #436 should address this portion of the upstream CI failures.  I think maybe we held off on merging it since @anissa111 was working on some other parts of the upstream CI failures and was just going to include this as well.  

At this point it might help to just get that merged though, it was just a one liner.  I updated the PR will mark as ready for review.  

And sorry if you've already figured this all out - just figured I'd try to save you some digging, since I did look into this part a while back.

**Comment by anissa111** [comment]
> > Upstream-dev CI failing at `install geocat-comp` step
> > `ERROR: Package 'geocat-comp' requires a different Python: 3.12.0 not in '<3.12,>=3.9'`
> > Currently, python version enforced as `python>=3.9, <3.12` in:
> > 
> > * [setup.cfg:28](https://github.com/NCAR/geocat-comp/blob/main/setup.cfg?rgh-link-date=2023-10-26T21%3A29%3A51Z)
> > * [docs.yml:5](https://github.com/NCAR/geocat-comp/blob/main/build_envs/docs.yml?rgh-link-date=2023-10-26T21%3A29%3A51Z)
> > * [environment.yml:5](https://github.com/NCAR/geocat-comp/blob/main/build_envs/environment.yml?rgh-link-date=2023-10-26T21%3A29%3A51Z)
> 
> Looks like this is the prior issue now getting worse.
> 
> @philipc2's fix in #436 should address this portion of the upstream CI failures. I think maybe we held off on merging it since @anissa111 was working on some other parts of the upstream CI failures and was just going to include this as well.
> 
> At this point it might help to just get that merged though, it was just a one liner. I updated the PR will mark as ready for review.
> 
> And sorry if you've already figured this all out - just figured I'd try to save you some digging, since I did look into this part a while back.

Yeah, that was the case. I'm re-running the tests on Philip's branch and we can merge that to fix for now since I am no longer currently working on the CI stuff.
