### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#447]
Related to #440

In addition to adding a repo-specific contributors guide, we should also add a code of conduct

**Comment by kafitzgerald** [comment]
Linking to the [UCAR Codes of Conduct](https://www.ucar.edu/who-we-are/ethics-integrity/codes-conduct) for reference and the [Project Pythia ](https://projectpythia.org/code_of_conduct.html) one derived from that.
