### ISSUE TITLE
[Release]: 2023.09.0

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#452]
## For Package Leader

Version: v2023.09.0
Requested Release Date: Thursday, September 7, 2023
Plain text summary of significant changes:
This release adds custom_seasons to climatology_average and adds a new Contributor's Guide to the documentation.

## Release progress checklist

- [x] CI tests are passing
- [x] release-notes.rst has been updated with latest release notes
- [x] a new tag and release has been made on GitHub
- [x] feedstock PR has been merged
- [x] release on pypi action has been triggered on the tag
- [x] new version can be installed via pip
- [x] new version can be installed via conda

**Comment by kafitzgerald** [comment]
We should probably make sure to get the xarray version pin in there as well.

**Comment by anissa111** [comment]
> We should probably make sure to get the xarray version pin in there as well. 

Yeah, agreed

**Comment by anissa111** [comment]
Released and verified!

**Comment by kafitzgerald** [comment]
> > We should probably make sure to get the xarray version pin in there as well.
> 
> Yeah, agreed

It looks like this didn't happen.  Do we want to fix that?

I probably should've opened an issue over there at the time.  I can do that now.
