### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#455]
Updates to the PR template (`.github/PULL_REQUEST_TEMPLATE.md`):
- remove item about tagging the entire NCAR/geocat team
- update link to contributor's guide (depends on #450)
- add a note to squash and merge if appropriate for cleaning up commit history
- remove link to non-existent "documentation standards" on geocat website
- Reword the "add summary here" comment at top to indicate a written summary should be added in the section in addition to noting the corresponding issue

**Comment by cyschneck** [comment]
Changes to the PR template (`.github/PULL_REQUEST_TEMPLATE.md`):

- [ ] remove item about tagging the entire NCAR/geocat team
- [x] update link to contributor's guide (depends on #450)
- [ ] add a note to squash and merge if appropriate for cleaning up commit history
- [x] "remove link to non-existent "documentation standards" on geocat website" -> set to Docstrings description in [contributions docstrings](https://geocat-comp.readthedocs.io/en/stable/contrib.html#docstrings)
- [ ] Reword the "add summary here" comment at top to indicate a written summary should be added in the section in addition to noting the corresponding issue
