### ISSUE TITLE
Convert all unit tests to pytest

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#462]
Existing tests (geocat-comp/test)

- [ ] [test_climatologies.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_climatologies.py)
- [ ] [test_fourier_filters.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_fourier_filters.py)
- [ ] [test_gradient.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_gradient.py)
- [ ] [test_interpolation.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_interpolation.py)
- [ ] [test_meteorology.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_meteorology.py)
- [ ] [test_spherical.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_spherical.py)
- [ ] [test_stats.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_stats.py)

C/I Workflow
- [ ] [ci.yml](https://github.com/cyschneck/geocat-comp/blob/main/.github/workflows/ci.yml)

**Comment by cyschneck** [comment]
Existing tests (geocat-comp/test)

- [test_climatologies.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_climatologies.py)
- [test_fourier_filters.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_fourier_filters.py)
- [test_gradient.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_gradient.py)
- [test_interpolation.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_interpolation.py)
- [test_meteorology.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_meteorology.py)
- [test_spherical.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_spherical.py)
- [test_stats.py](https://github.com/NCAR/geocat-comp/blob/main/test/test_stats.py)

**Comment by cyschneck** [comment]
Good overview about the advantages of Pytest over Unittest: [Unittest vs. Pytest](https://pytest-with-eric.com/comparisons/pytest-vs-unittest/#Comparison-Table-%E2%80%94-Unittest-vs-Pytest)
