### ISSUE TITLE
📖 Research spectral analysis functionality

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#487]
Related #124 

See:
- NCL applications' [spectral analysis page](https://www.ncl.ucar.edu/Applications/spec.shtml)
- [xrft](https://xrft.readthedocs.io/en/latest/index.html)
- Original functions:
  -   [specx_anal](http://www.ncl.ucar.edu/Document/Functions/Built-in/specx_anal.shtml)
  -   [specxy_anal](http://www.ncl.ucar.edu/Document/Functions/Built-in/specxy_anal.shtml)
  -   [specx_ci](http://www.ncl.ucar.edu/Document/Functions/Built-in/specx_ci.shtml)

**Comment by jukent** [comment]
I took some notes of the conversation on this I could follow so far and resources to use: https://docs.google.com/presentation/d/1leJPULjcyOx0nQ81gUZ597wqiTwoeAFJlue3bYSmU9Y/edit?usp=sharing 

It seems like all the functionality exists in `numpy` and `scipy` (but without an example) except the theoretical Markov spectrum and lower and upper confidence curves, all found in `specx_ci` (confidence interval) -- however the link to this function always gives me a 404.

I'll start with the simpler `specx_1.ncl` script, try to replicate it with `numpy` and `scipy`, then investigate `specx_ci` more thoroughly which is needed for `specx_5.ncl`, and has the more missing components of a spectral analysis workflow in Python.

**Comment by jukent** [comment]
Putting research in a Jupyter Notebook to move into sample workflows. https://geocat-comp--523.org.readthedocs.build/en/523/examples/specxy_anal.html
