### ISSUE TITLE
`interp_multidim` can change data precision

### ISSUE THREAD

**Issue by brianpm** [NCAR/geocat-comp#488]
When using `interp_multidim` the interpolated data precision can change based on the coordinate variable precision.

Specifically, we this came up in an ADF issue (https://github.com/NCAR/ADF/issues/192) where it was noted that data variables were getting promoted to double from single. 

It appears that this occurs whenever either the source or destination coordinate variables are double.

**Example that demonstrates the behavior**
```python
import numpy as np
import xarray as xr
import geocat.comp as gc

rng = np.random.default_rng()
fake_data = rng.random((90, 180), dtype=np.dtype('float32'))  
fake_data = xr.DataArray(fake_data, coords={"lat":np.linspace(-89, 89, 90), "lon":np.linspace(0,360-2,180)})
tgt_grid = xr.Dataset(coords={"lat":np.linspace(-89, 89, 45), "lon":np.linspace(0,360-4,90)})
regridded_data = gc.interp_multidim(fake_data, tgt_grid.lat.values, tgt_grid.lon.values, cyclic=True)
print(f"With float64 coordinates (all): original dtype: {fake_data.dtype}, output dtype: {regridded_data.dtype}")

fake_data = fake_data.assign_coords({"lat":np.linspace(-89, 89, 90).astype('float32'), "lon":np.linspace(0,360-2,180).astype('float32')})
tgt_grid = xr.Dataset(coords={"lat":np.linspace(-89, 89, 45), "lon":np.linspace(0,360-4,90)})
regridded_data = gc.interp_multidim(fake_data, tgt_grid.lat.values, tgt_grid.lon.values, cyclic=True)
print(f"Input coords are {fake_data.lat.dtype}, output coords are {tgt_grid.lat.dtype}: original dtype: {fake_data.dtype}, output dtype: {regridded_data.dtype}")

fake_data = fake_data.assign_coords({"lat":np.linspace(-89, 89, 90).astype('float32'), "lon":np.linspace(0,360-2,180).astype('float32')})
tgt_grid = xr.Dataset(coords={"lat":np.linspace(-89, 89, 45).astype('float32'), "lon":np.linspace(0,360-4,90).astype('float32')})
regridded_data = gc.interp_multidim(fake_data, tgt_grid.lat.values, tgt_grid.lon.values, cyclic=True)
print(f"Input coords are {fake_data.lat.dtype}, output coords are {tgt_grid.lat.dtype}: original dtype: {fake_data.dtype}, output dtype: {regridded_data.dtype}")

fake_data = fake_data.assign_coords({"lat":np.linspace(-89, 89, 90), "lon":np.linspace(0,360-2,180)})
tgt_grid = xr.Dataset(coords={"lat":np.linspace(-89, 89, 45).astype('float32'), "lon":np.linspace(0,360-4,90).astype('float32')})
regridded_data = gc.interp_multidim(fake_data, tgt_grid.lat.values, tgt_grid.lon.values, cyclic=True)
print(f"Input coords are {fake_data.lat.dtype}, output coords are {tgt_grid.lat.dtype}: original dtype: {fake_data.dtype}, output dtype: {regridded_data.dtype}")
```
**Result**
```
With float64 coordinates (all): original dtype: float32, output dtype: float64
Input coords are float32, output coords are float64: original dtype: float32, output dtype: float64
Input coords are float32, output coords are float32: original dtype: float32, output dtype: float32
Input coords are float64, output coords are float32: original dtype: float32, output dtype: float64
```

**Expected behavior**
The precision of the data should be preserved.

**Environment**
I don't think versions matter much for this, but I'm using:
- numpy 1.24.4
- xarray 2023.2.0
- geocat-comp 2023.10.0

I think this problem originates from the xarray methods being used, so maybe we need to ask them about it, too (?).

**Comment by kafitzgerald** [comment]
Forgot to grab this earlier when I started taking a look (sorry Anissa), but it seems like this behavior comes from another layer down in the interpolation routines in either in SciPy (or potentially Numpy in some cases).  And interestingly enough, depending upon the routine used the behavior seems to be different.  `np.interp` converts to float64 regardless of the input types.

Are you concerned about the calculations being done in double precision or just the return dtype being inconsistent with the source?  

Somewhat related: 
* https://github.com/pydata/xarray/issues/4770

**Comment by brianpm** [comment]
My guess is that the concern is mostly about the return dtype. In our case, the output is being saved to disk in netCDF files, so the promotion increases the file size. So we could just reduce to float32 if we need to. I can't imagine that this would introduce any detrimental behavior... I'll try to follow up within the ADF group to see if there are any concerns I'm not thinking about.

**Comment by kafitzgerald** [comment]
Sounds good.

In the discussion on the xarray issue mentioned above they talk about a performance plenty w/ the conversion back to the original dtype (in that case int32) so I'd be hesitant to include this with the interpolation (in all cases anyway), but certainly seems reasonable to do after if file size is the concern.

**Comment by brianpm** [comment]
Thanks for looking into this issue!

I have confirmed that the concern reported in https://github.com/NCAR/ADF/issues/192 was related to whether the calculation was correct. 

I'm inclined to close that issue and this one since I think we've got confidence the calculation is correct. It is potentially unexpected behavior, so I'd also suggest mentioning it in documentation.
