### ISSUE TITLE
geocat.comp.meteorology.delta_pressure is different with dpres_plev

### ISSUE THREAD

**Issue by cccccoldrun** [NCAR/geocat-comp#538]
###this is the ncl  code
plev = (/ 1000.,950.,900.,850.,800.,750.,700.,650.,600., \
    550.,500.,450.,400.,350.,300.,250.,200., \
    175.,150.,125.,100., 80., 70., 60., 50., \
     40., 30., 25., 20. /)

plev       = plev*100.        
plev@units = "Pa"        ; Pa   =  kg/(m s2) (Pascal)

ptop       = min(plev)    

psfc       = 850*100.           
psfc@units = "Pa" 

dp   = dpres_plevel(plev, psfc, ptop, 0)  ; dp(30)
print(dp)

##this is the python code:
import geocat.comp as gc
import numpy as np 
plev = [ 1000.,950.,900.,850.,800.,750.,700.,650.,600., \
    550.,500.,450.,400.,350.,300.,250.,200., \
    175.,150.,125.,100., 80., 70., 60., 50., \
     40., 30., 25., 20. ]
plev       = np.array(plev)*100.        
ptop       = min(plev)    
psfc       = 850*100.           
dp   = gc.meteorology.delta_pressure(plev, psfc)  
print(dp)

but the result is different if the psfc is lower than the first value of plev
![屏幕截图 2024-01-05 162143](https://github.com/NCAR/geocat-comp/assets/98377186/649ccf69-99cc-4a99-9b33-8d182814cc21)
![屏幕截图 2024-01-05 162521](https://github.com/NCAR/geocat-comp/assets/98377186/fe282ef1-360f-49d1-b9b4-01c36dd0339a)

**Comment by kafitzgerald** [comment]
Thanks, @cccccoldrun! 

I looked into this briefly and confirmed we don't account for this case (where the specified surface pressure (psfc) is less than some values of the given pressure levels (plev)).  

Instead of assigning a missing/fill value like the NCL routine, `gc.meteorology.delta_pressure` attempts to compute those values.

It'd be good to get a fix in for this and get test coverage.

**Comment by bnepal22** [comment]
Hello @all I am confuse, does computing thickness between two pressure level here based on hypsometric equation or its jjust simple difference between two pressure level. As in the shared result above , the 3rd value why it is 2500 if its the difference between 85000-80000, similarly for the  16th value why its 3750 and so on. Could you kindly please clarify this. I am completely confuse.

**Comment by cccccoldrun** [comment]
Actually, if you have seen the code about the function,the top and bottom is different from the mid layers.
3750 is (25000-17500)/2
bottom:2500 is 850000(surface pressure)-(85000+80000)/2
top:250 (2500+2000)/2-2000(top pressure)

________________________________
