### ISSUE TITLE
Update assets to comply with the New NSF Branding Theme

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#540]
Update documentation site, pages, etc. to reflect the NSF branding policy changes (e.g. NSF NCAR) whereever applicable, e.g. logos,  text, etc.

**Comment by erogluorhan** [comment]
@cyschneck I just noticed a small issue with the logo:

<img width="531" alt="image" src="https://github.com/NCAR/geocat-comp/assets/32553057/c269daf5-785f-412c-bd54-f5baa4f3b831">

"NCAR" is not visible with the light version of it; the dark version could be better.

**Comment by kafitzgerald** [comment]
Shoot!  I'll have to fix this over on viz as well.  It looks like the "light" logos are for use with dark themes.  

Our dark theme in general is pretty tough to read as well (w/ the navy headers).  That's another issue though.

**Comment by cyschneck** [comment]
This was handy, let's the theme decide which version of the logo to use:
```
html_theme_options = {
    "logo": {
        "image_light": "_static/images/logos/NSF_NCAR_light.png",
        "image_dark": "_static/images/logos/NSF_NCAR_dark.png",
    }
}
```

**Comment by erogluorhan** [comment]
This is cool!
