### ISSUE TITLE
Packaging updates needed for namespace packages

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-comp#547]
Setuptools has deprecated `pkg_resources.declare_namespace` ([see here](https://setuptools.pypa.io/en/latest/history.html#v67-3-0)).  We currently use this.

It looks like the recommendation is now to use implicit namespace packaging as described in [PEP 420](https://peps.python.org/pep-0420), but that this [will need to be coordinated across distributions](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages).

**Comment by cyschneck** [comment]
Seems like using [Custom Discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) works the setup.cfg files. Replaces `package` with `package_dir` and includes `packages = find_namespace:`
