### ISSUE TITLE
Distributing geocat via PyPI/pip

### ISSUE THREAD

**Issue by andersy005** [NCAR/geocat-comp#57]
As it's been pointed out in this comment on [Discus](http://disq.us/p/27q4m1e), **the only way to use geocat today is via conda**. This may end up penalizing/discouraging non-conda users or may force them to migrate to conda --which is not convenient for everyone-- if they really want to use geocat. It would be useful to consider building and publishing **wheels** to PyPI. 

@khallock pointed out:

> In the past, we provided binary releases of our NCL-related software, but doing so means that we have to maintain a large collection of build environments (particularly for different flavors of Linux)

However, it's my understanding that this process can be less time consuming when done via automation. In the past, I've used GitHub actions in conjunction with [cibuildwheel](https://github.com/joerick/cibuildwheel) to build wheels for windows, MacOS, Linux, and to publish them to PyPI. 

Let me know if this is of interest, and I will open a PR.

Cc @matt-long, @kmpaul

P.S.: I wasn't sure whether this is the right repo to raise this issue in. Let me know if there's an appropriate place for this discussion.

**Comment by clyne** [comment]
Good points, @andersy005. Thanks for bringing this up. The GeoCAT will definitely discuss f2f.

**Comment by andersy005** [comment]
Now that `geocat-f2py` is an optional dependency,  It's my understanding that publishing `geocat-comp` to PyPI is now feasible, and should be straightforward.
