### ISSUE TITLE
Upstream CI failing: March 17 2024

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#580]
See logs here:
https://github.com/NCAR/geocat-comp/actions/runs/8319362892

It seems like the only package that "officially" updated from yesterday is `libxml2: 2.12.5 -> 2.12.6`, so I'm not sure what's going on there.

EDIT: Looking at the environments some more, pandas also updated `3.0.0.dev0+538.gd4ddc805a0 -> 3.0.0.dev0+546.g9eb1553566`, which seems more likely to be the culprit.

It might be related to https://github.com/numpy/numpy/issues/25275, in which case it seems like they'll sort it out in a few days

**Comment by kafitzgerald** [comment]
Ah, yeah the numpy issue looks like it could be it.  We've had similar failures over on geocat-examples (see NCAR/geocat-examples#597).

**Comment by anissa111** [comment]
Looks like it's sorted itself out!
