### ISSUE TITLE
ESMF_regrid

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#6]
Port the NCL **ESMF_regrid** family of functions, including: ESMF_regrid. The **ESMF_regrid** function regrids data from one lat/lon grid to another, using ESMF software.

**Comment by maboualidev** [comment]
@clyne @khallock Have you checked this:
https://xesmf.readthedocs.io/en/latest/

**Comment by clyne** [comment]
I’m aware it exists, but don’t know much about it. What I’ve hear from a number of scientists wrt ESMF regridding is that there are Python tools out there, but they are either too difficult to use or don’t provide desired functionality. This is an area where we probably need to get some community input and do some homework before diving in with implementation. Matt Long might be a good place to start. Posting something to the NCL mailing list is another option.

jc


> On Oct 23, 2019, at 10:12 AM, Mohammad Abouali <notifications@github.com> wrote:
> 
> @clyne @khallock Have you checked this:
> https://xesmf.readthedocs.io/en/latest/
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by dcherian** [comment]
FYI xesmf development is continuing here: https://github.com/pangeo-data/xESMF

**Comment by dcherian** [comment]
(I don't understand how I can unassign someone)

**Comment by anissa111** [comment]
Closing this in favor of development/implementation elsewhere

**Comment by anissa111** [comment]
Closing this in favor of development/implementation elsewhere
