### ISSUE TITLE
User-defined missing values in functions

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#60]
**FUNCTIONS WITH THE BUG:**
`rcm2points, rcm2rgrid, rgrid2rcm` at Cython level (in [_ncomp.pyx](https://github.com/NCAR/geocat-comp/blob/develop/src/geocat/comp/_ncomp.pyx)) as well as their test cases under /test.

**BUG EXPLANATION:**
At Cython level, functions such as linint2, linint2points, and moc_globe_atl has the following code block, which works correctly to handle both NaN/None and user-defined missing values:

```
replace_fi_nans = False

    if msg is None or np.isnan(msg): # if no missing value specified, assume NaNs
        missing_inds_fi = np.isnan(fi.numpy)
        msg = get_default_fill(fi.numpy)
        replace_fi_nans = True
    else:
        missing_inds_fi = (fi.numpy == msg)

    set_ncomp_msg(&(fi.ncomp.msg), msg) # always set missing on fi.ncomp

    if missing_inds_fi.any():
        fi.ncomp.has_missing = 1
        fi.numpy[missing_inds_fi] = msg 
```

However, three functions (`rcm2points, rcm2rgrid, rgrid2rcm`) have the same code block slightly modified as follows:

```
replace_fi_nans = False

    if msg is None or np.isnan(msg): # if no missing value specified, assume NaNs
        missing_inds_fi = np.isnan(fi.numpy)
        msg = get_default_fill(fi.numpy)
        replace_fi_nans = True

    set_ncomp_msg(&(fi.ncomp.msg), msg) # always set missing on fi.ncomp

    if replace_fi_nans and missing_inds_fi.any():
        fi.ncomp.has_missing = 1
        fi.numpy[missing_inds_fi] = msg
```

which first results in errors in setting the `has_missing` fields and actual missing value of the input array and that eventually results in errors for the output array. Such errors have been validated for [test_rcm2points.py](https://github.com/NCAR/geocat-comp/blob/develop/test/test_rcm2points.py) / `test_rcm2points_msg_float64()`.

The above error should be resolved first, then the corresponding test cases (i.e. a few test cases in test script of each function) should be corrected.

**Comment by clyne** [comment]
Good catch, @erogluorhan! Is there a reason we can't define a utility function to consistently handle missing values, reduce cut-n-paste code, etc?

**Comment by erogluorhan** [comment]
Good suggestion, @clyne. I agree with it and will try to come up with such a solution when I walk through the code for this issue.

**Comment by pilotchute** [comment]
Locations of the errors are:
```
./geocat-comp/src/geocat/comp/_ncomp.pyx:893:    if replace_fi_nans and missing_inds_fi.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1007:    if replace_fi_nans and missing_inds_fi.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1106:    if replace_fi_nans and missing_inds_fi.any():
```

**Comment by pilotchute** [comment]
Additional locations to look at are:
```
./geocat-comp/src/geocat/comp/_ncomp.pyx:786:    if replace_psfc_nans and missing_inds_psfc.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:803:    if replace_psfc_nans and psfc.ncomp.has_missing:
./geocat-comp/src/geocat/comp/_ncomp.pyx:893:    if replace_fi_nans and missing_inds_fi.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:910:    if replace_fi_nans and fi.ncomp.has_missing:
./geocat-comp/src/geocat/comp/_ncomp.pyx:1007:    if replace_fi_nans and missing_inds_fi.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1024:    if replace_fi_nans and fi.ncomp.has_missing:
./geocat-comp/src/geocat/comp/_ncomp.pyx:1106:    if replace_fi_nans and missing_inds_fi.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1123:    if replace_fi_nans and fi.ncomp.has_missing:
./geocat-comp/src/geocat/comp/_ncomp.pyx:1230:    if replace_data_nans and missing_inds_data.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1244:    if replace_data_nans and data.ncomp.has_missing:
./geocat-comp/src/geocat/comp/_ncomp.pyx:1316:    if replace_z_nans and missing_inds_z.any():
./geocat-comp/src/geocat/comp/_ncomp.pyx:1330:    if replace_z_nans and z.ncomp.has_missing:
```

**Comment by pilotchute** [comment]
Branch [Issue_60](https://github.com/NCAR/geocat-comp/tree/Issue_60) created.
- [X] Updates to [_ncomp.pyx](https://github.com/NCAR/geocat-comp/blob/Issue_60/src/geocat/comp/_ncomp.pyx)
- [ ] Updates to Test_<method>.py files.

**Comment by pilotchute** [comment]
@khallock @erogluorhan why are we using msg=None at the method definitions when we assume that None can mean np.nan later?

**Comment by erogluorhan** [comment]
This is because the default case should be that user calls functions without providing any specific value for `msg (i.e. `msg = None`)`. In this case `np.nan` values in the input arrays should still be processed as missing values. In other words, there should be no difference between the cases where user either does not provide any missing value as input (i.e. `msg = None`) or gives `msg = np.nan` as input.

**Comment by pilotchute** [comment]
Closing and migrating to [ncomp#3](https://github.com/NCAR/geocat-ncomp/issues/3)
