### ISSUE TITLE
Retaining meta data information in functions

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#61]
**FUNCTIONS CONSIDERED IN THIS ISSUE:**
`linint2points, rcm2points, rcm2rgrid, rgrid2rcm, triple2grid, grid2triple`

**ISSUE:**
It can be seen from the function `linint2` that when the argument `meta` is set True, the meta data information from the input data should be retained in the output data. 

Such retainment of meta data was handled in NCL by additional functions with a name extension of `_Wrap`. For example, `linint2` is the original function without any meta data retainment. `linint2_Wrap`does exactly the same computations with `linint2`, but it also retains meta information from input array (`fi`) in the output array (`fo`).

For a function that already has a `_Wrap` additional function in NCL, the default value of the `meta` argument should be set `True` in Python API, and meta information should be retianed as a default (as can be seen in `linint2`). However, this meta data handling was not supported in the aforementioned functions (`linint2points, rcm2points, rcm2rgrid, rgrid2rcm, triple2grid, grid2triple`) so far. All of these functions except `grid2triple` has a `_Wrap` counterpart function in NCL so that meta data retainment should be supported for these functions also in the Python API. In addition, `grid2triple` function should be investigated to see whether it is possible to support meta data retainment for it.

**Comment by clyne** [comment]
@khallock, is there a reason to not simply always copy the attribute metadata to the output array when possible? Do we even need this option, or should we simply always copy out the metadata when possible? Sorry for not thinking of this earlier.

We need to remember to assign this issue to Austin once his GitHub account is set up.

**Comment by khallock** [comment]
@clyne That's a great question, thanks for bringing it up! I'm of the opinion that keeping the optional `meta=` keyword argument, setting it to `True` by default, is the most flexible option for the most users. If a user knows that they won't need metadata, then this could potentially save them a non-trivial amount of memory, particularly for large coordinate arrays. This is just my gut feeling on the matter, but perhaps it's worth discussing further in our next team meeting?

**Comment by clyne** [comment]
Most attributes are only a few bytes in size. In the case of coordinate arrays isn't it only the name of the coordinate array that is copied, not the coordinate values themselves?

**Comment by khallock** [comment]
Great point, most attributes are scalars or short strings and are thus a non-issue in terms of memory usage. Regarding coordinate arrays, however, in the case of [linint2](https://github.com/NCAR/geocat-comp/blob/develop/src/geocat/comp/__init__.py#L262-L268), [eofunc](https://github.com/NCAR/geocat-comp/blob/develop/src/geocat/comp/__init__.py#L662-L673), and [eofunc_ts](https://github.com/NCAR/geocat-comp/blob/develop/src/geocat/comp/__init__.py#L796-L804) the coordinate arrays themselves are actually being copied in addition to the dimension names.

This raises another interesting question though... should we consider copying dimension names and attributes regardless of `meta=True` or `meta=False`, or alternatively should we consider possibly using a different keyword argument specifically for handling coordinate arrays?

**Comment by clyne** [comment]
If the genesis of the NCL "_W" functions was to save memory or compute I'm not sure that argument still applies for most of these operators. Even for the examples above that copy over coordinate arrays these are only 1D variables. I'd opine that moving forward we not carry over the meta option from NCL and simply default to always coping attributes. If there are cases where there is truly a significant memory or compute savings we can address those as needed.

Thoughts?
