### ISSUE TITLE
[💡]: Is there a function to compute the derivative of a field

### ISSUE THREAD

**Issue by ABF-EC** [NCAR/geocat-comp#634]
### Describe the functionality you are requesting, linking any relevant usage or previous implementations in the python ecosystem or otherwise.

Hi,
I am looking for a function to compute the derivative of a field. I was wondering if you have a function that calculates the derivative of a field in any of your python library.
There were some derivative functions in NCL, but I don't think I have seen any in geocat-comp.
Best regards,

### Is this a request for functionality that was previously in NCL?

Yes

**Comment by ABF-EC** [comment]
Thanks Katelyn!

I will have a look this week at those and come back to you by the end of the week.

**Comment by anissa111** [comment]
Hello [ABF-EC](https://github.com/ABF-EC), did you find what you were looking for?

I will close this issue shortly if you do not need anything else here.

**Comment by anissa111** [comment]
I'm going to close this for now, feel free to re-open if there's anything else.

**Comment by ABF-EC** [comment]
Hi Anissa,
Sorry for the late response.
Yes, I can work with what Katelyn proposed.
Thank you!
