### ISSUE TITLE
Windows release failures

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#655]
Looks like our release is having trouble on windows. See first [failure log](https://github.com/NCAR/geocat-comp/actions/runs/11694686950) from today.

Logging this here for now to look into in the morning.

**Comment by kafitzgerald** [comment]
Looks like we're hitting this: https://github.com/mamba-org/mamba/issues/3576

**Comment by anissa111** [comment]
Closing this now, it sorted itself out
