### ISSUE TITLE
month_to_season

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#7]
Port the NCL **month_to_season** family of functions, including: Month_to_season, month_to_seasonN, month_to_season12. The **month_to_season** function computes a user-specified three-month seasonal mean (DJF, JFM, FMA, MAM, AMJ, MJJ, JJA, JAS, ASO, SON, OND, NDJ).

**Comment by bonnland** [comment]
@khallock  I have a possible implementation of month_to_season.   If you think it suits your needs, I would need a little guidance on where you want the code to appear before submitting a pull request.  Perhaps you want tests included too.   

You can test out the code using the lines below the function.

```python
def month_to_season(xMon, season):
    """ This function takes an xarray dataset containing monthly data spanning years and
        returns a dataset with value per year, for a specified three-month season.

        Time stamps are centered on the season, e.g. seasons='DJF' returns January timestamps.
    """
    import pandas as pd
    seasons_pd = {'DJF': 'QS-DEC', 'JFM': 'QS-JAN', 'FMA': 'QS-FEB', 'MAM': 'QS-MAR', 'AMJ': 'QS-APR', 'MJJ': 'QS-MAY',
                  'JJA': 'QS-JUN', 'JAS': 'QS-JUL', 'ASO': 'QS-AUG', 'SON': 'QS-SEP', 'OND': 'QS-OCT', 'NDJ': 'QS-NOV'}
    try:
        season_pd = seasons_pd[season]
    except KeyError:
        raise ValueError("contributed: month_to_season: bad season: SEASON = " + season)
    month_offset = 'MS'
    xSea = xMon.resample(time=season_pd, loffset=month_offset).mean()
    return xSea
```

Test code: 
```python
import xarray as xr

ds = xr.tutorial.open_dataset('rasm')
ds
ds['time']

x = month_to_season(ds, 'JAS')
x
x['time']
```

**Comment by bonnland** [comment]
One eventual improvement to the code is to filter data before computing means for a single season.   The code as it is now, computes means for four seasons and filters down to one, which is more resource intensive than necessary.
