### ISSUE TITLE
Move extended examples from GeoCAT-comp to GeoCAT-examples

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#72]
We should consider migrating the extended (standalone Python script) examples from the GeoCAT-comp repo. to the GeoCAT-examples repo

**Comment by erogluorhan** [comment]
This is going to be addressed once PR #128 and [GeoCAT-examples PR #316](https://github.com/NCAR/GeoCAT-examples/pull/316) are merged.
