### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by andersy005** [NCAR/geocat-comp#73]
Now that the code that wraps the fortran routines reside in geocat-ncomp, the existing contribution guide appears to be outdated. It would be nice to have an up-to-date contribution guide.

**Comment by clyne** [comment]
Indeed. This is HIGH on the priority list.

**Comment by erogluorhan** [comment]
Added, please see: [GeoCAT Contributor's Guide](https://geocat.ucar.edu/pages/contributing.html) as well as repository-specific documentation for GeoCAT-comp, GeoCAT-ncomp, and libncomp.
