### ISSUE TITLE
Dose the geocat-comp support Windows?

### ISSUE THREAD

**Issue by LuckyBoy314** [NCAR/geocat-comp#85]
I failed to install it on my Win7

**Comment by erogluorhan** [comment]
Hi there! Thank you for your question! It does not support Windows yet; however, we are investigating this for future.

**Comment by pilotchute** [comment]
@LuckyBoy314 We are making improvements which will make a windows version possible, I'll message you here once one is released.

**Comment by LuckyBoy314** [comment]
@erogluorhan @pilotchute Thank you for your reply and excellent work！ I have installed it on my Ubuntu VM, but I'm still looking forward to the Windows version.
