### ISSUE TITLE
problem in geocat.viz

### ISSUE THREAD

**Issue by pedrotildes** [NCAR/geocat-comp#92]
I'm trying to use the geocat examples and I'm always stuck in erros in geocat.viz.util:

AttributeError: module 'geocat.viz.util' has no attribute 'add_major_minor_ticks'

I have installed Geocat in macOS Big Sur with anaconda3.8 and I have also installed geocat-viz in the conda environment where geocat was installed
Any hints?
Thanks

**Comment by michaelavs** [comment]
Hi @pedrotildes,
Were you able to resolve this issue or do you still need assistance?
If you do still need assistance, would you mind including part, or all, of the code you are using (including import statements from the top)?
